# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce8872f3952bf31f203a6b2ed55441279d9f0056ae6a7b98fc6ca6e82ba84398f866806dfdd954617db1f8ad404f89d02c8e637600685db44ad6ecf03bf7f69a

test:
  secret_key_base: e46dddd2a576870ea0d7d71cd18a421f2598fc1284b7bf52938161f10fbf3ad17c847cf6a84b4d70959d3c3aae5d13b2c96bf15fb616164a832f9c3e97481453

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
